set draw_borders true
set preview_images true
set colorscheme default
set wrap_scroll true

map n console touch%space
map <C-n> console mkdir%space

map c eval fm.open_console('rename ' + fm.thisfile.relative_path.replace("%", "%%"))
map <C-c> rename_append

map dd console delete

map gh cd ~
map gD cd ~/Downloads
map gP cd ~/Projects
